//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingOfResonantComponents.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account_Data()
        {
            this.Account = new HashSet<Account>();
            this.Remont = new HashSet<Remont>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Familia { get; set; }
        public string Device_Remont_type { get; set; }
        public string Raspisanie_work { get; set; }
        public Nullable<decimal> Zarplata { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remont> Remont { get; set; }
    }
}
