//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingOfResonantComponents.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remont
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_Account_Data { get; set; }
        public Nullable<int> Id_Detail { get; set; }
        public string Type_neispravnosti { get; set; }
        public string Device_names { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> Start_remonta_po_time { get; set; }
        public Nullable<System.DateTime> End_remonta_po_time { get; set; }
    
        public virtual Account_Data Account_Data { get; set; }
        public virtual Sclad Sclad { get; set; }
    }
}
