//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingOfResonantComponents.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sclad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sclad()
        {
            this.Remont = new HashSet<Remont>();
        }
    
        public int id { get; set; }
        public string Device_type { get; set; }
        public string Detali { get; set; }
        public Nullable<int> Kolichestvo { get; set; }
        public Nullable<System.DateTime> Pribitie_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remont> Remont { get; set; }
    }
}
