//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingOfResonantComponents.DbEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YchotRemontnihKomplektuishuhEntities : DbContext
    {
        public YchotRemontnihKomplektuishuhEntities()
            : base("name=YchotRemontnihKomplektuishuhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Account_Data> Account_Data { get; set; }
        public virtual DbSet<Remont> Remont { get; set; }
        public virtual DbSet<Sclad> Sclad { get; set; }
    }
}
